[theme]
base="light"
primaryColor = "#f63366"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#262730"
font = "monospace"

[server]
# enableStaticServing = true

[client]
toolbarMode = "minimal"
# toolbarMode = "auto"