[theme]
base="dark"
primaryColor = "#17428d"
backgroundColor="#fff"
secondaryBackgroundColor="#1F458F"
textColor="#fff"
font = "monospace"

[server]
# enableStaticServing = true

[client]
# toolbarMode = "minimal"
toolbarMode = "auto"