[theme]
base="dark"
primaryColor = "#F0F0F0"
backgroundColor="#fff"
secondaryBackgroundColor="#fff"
textColor="#000"
font = "monospace"

[server]
# enableStaticServing = true

[client]
# toolbarMode = "minimal"
toolbarMode = "auto"